// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/Yoway1994/LineChatGPT3/config"
	"github.com/Yoway1994/LineChatGPT3/domain"
	"github.com/Yoway1994/LineChatGPT3/internal/line"
	"github.com/Yoway1994/LineChatGPT3/internal/openAI"
	"github.com/line/line-bot-sdk-go/linebot"
	"github.com/sashabaranov/go-gpt3"
	"log"
	"sync"
)

// Injectors from wire.go:

func NewOpenAI() (domain.OpenAI, error) {
	config := NewConfig()
	client := NewChatGpt3(config)
	domainOpenAI := openAI.NewOpenAI(client)
	return domainOpenAI, nil
}

// wire.go:

var cg *config.Config

var configOnce sync.Once

func NewConfig() *config.Config {
	configOnce.Do(func() {
		log.Println("read config")
		cg = config.NewConfig()
		log.Println("read config success")
	})
	return cg
}

var bot *linebot.Client

var botOnce sync.Once

func NewLineBot() *linebot.Client {
	botOnce.Do(func() {
		log.Println("init line bot")
		bot = line.NewBot(cg)
		log.Println("init line bot success")
	})
	return bot
}

var gpt *gogpt.Client

var gptOnce sync.Once

func NewChatGpt3(cg2 *config.Config) *gogpt.Client {
	gptOnce.Do(func() {
		log.Println("init gpt3")
		gpt = openAI.NewClient(cg2)
		log.Println("init gpt3")
	})
	return gpt
}
